### ISSUE TITLE
We need a Cover for Twitter

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/mozillach_branding#6]
We need a cover picture for twitter to make it a little bit more beautiful. @freaktechnik suggested to print out a mozilla logo and take a picture of it in front of a landscape. Since he said he might have time to do that, I'm assigning this directly to him.

**Comment by freaktechnik** [comment]
I've shot a few pictures: https://www.dropbox.com/sc/qr01vnm1vvq5330/AAAkZFbDWVw1Pn2PyFi5Wd5oa (eww, Dropbox, I know).

I've picked out a picture that fit a few criteria and set it as our current cover (see https://twitter.com/mozillaCH ):
- Can be cut to a 3:1 aspect ratio while still containing the symbol and not feeling cut-off
- The logo isn't too far from the edge to be cut off on clients that still use the old ratio (something around 2:1)

I've not yet colour-corrected the logo in that picture. I'm not sure it makes sense to correct it, since correction can create very weird looking images due to shadows.

What do you think of our current cover?

**Comment by freaktechnik** [comment]
All the okay-ish images I took for the header and some extras are now in this repo (hopefully with git-lfs).
